pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'.""
  branches:
    master:
      - step:
          script:
            - echo "This script runs only on commit to the MASTER branch."
            - uname -a
            - free -m
            - df -H
            - netstat -apn
            - docker info
            - npm -v
            - printf "Everything is awesome!\n";
    dev-1.0.2:
      - step:
          script:
            - echo "This script runs only on commit to the dev-1.0.2 branch."
            - uname -a
            - apt-get update
            - apt -y install php5 php5-cli php5-common 
            - git clone https://bitbucket.org/tbaltrushaitis/mp3web mp3web
            - cd mp3web
            - CODE_VERSION="$(cat ./VERSION)"
            - printf "CODE_VERSION\t = \t ${CODE_VERSION}";
            - GIT_BRANCH="dev-${CODE_VERSION}";
            - git checkout ${GIT_BRANCH}
            - git branch
            - git pull
            - ls -als
            - find . -type f -exec chmod 664 {} \;
            - find . -type d -exec chmod 775 {} \;
            - find . -type f -name *.sh -exec chmod 775 {} \;
            - npm -v
            - npm i
            # - npm start
            # - npm run test
            # - npm run setup
            # - npm run build
            # - npm run deploy
            - pwd
            - php -v
            - which wget
            - which composer
            # - ./setup.sh test --env=production
            - ./setup.sh prepare --env=production
            - ./setup.sh build --env=production
            - ./setup.sh deploy --env=production
            - printf "Everything is awesome!\n";
