# image: tbaltrushaitis/ubuntu-nodejs:v8.0.0
image: php:7.1.22-fpm-jessie

pipelines:
  default:
    - step:
        name: Default Step
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'.\n"
  branches:
    master:
      - step:
          name: Default Step in Master
          script:
            - printf "[Step_00] This script runs only on commit to the MASTER branch.\n"
            - uname -a
            - free -m
            - df -H
            - netstat -apn
            - ls -als
            - pwd
            - printf "Everything is awesome!\n";
    dev-1.0.3:
      - step:
          name: [01] Greeting
          script:
            - printf "[Step_01] This script runs only on commit to the [${BITBUCKET_BRANCH}] branch.\n"
            - uname -a
            - pwd
            - printf "[Step_01] ==================================================================== [FINISHED]\n"
      - step:
          name: [02] Update system
          caches:
            - apt
            - bower
            - node
          script:
            - printf "Update system \n"
            - source ./bin/.bash_colors
            - apt-get -y update && apt-get -y upgrade
            - printf "System Updated!\n"
      - step:
          name: [03] Install system packages
          caches:
            - apt
          script:
            - apt -y install make curl
      - step:
          name: [04] PHP setup
          caches:
            - apt
          script:
            - printf "PHP setup \n"
            # PHP setup
            # - apt-get -y install php php-cli php-common php-dba
            # - apt search php
            # - sleep 10
            - php -v
      - step:
          name: [05] NVM install
          script:
            - printf "NPM install \n"
            # NPM install
            - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            - export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}nvm"
            # - \. "$NVM_DIR/nvm.sh" # This loads nvm
            - echo -e "\t${BCyan}ENV:\t exported [$NVM_DIR/nvm.sh]"
            # - command -v nvm
            # This loads nvm bash_completion
            # - . "$NVM_DIR/bash_completion"
      - step:
          name: [06] Setup NODE.JS
          script:
            - nvm install v10.0.0
            - node -v
      - step:
          name: [07] Build project
          caches:
            - bower
            - node
          script:
            - echo "BUILD project"
            - pwd
            # BUILD project
            - make setup
            - sleep 1
            - make engine
            - make dev
            - sleep 1
            - pwd && ls -als
            - cat webroot/.env
      - step:
          name: [08] Check webroot
          script:
            - cd webroot
            - cat INSPIRATION
      - step:
          name: [09] Finalize
          script:
            - echo "[Step_Info] Script runs on the [${BITBUCKET_BRANCH}] branch."
            - pwd
            - echo "[BITBUCKET_CLONE_DIR] = [${BITBUCKET_CLONE_DIR}]"
            - echo "[BITBUCKET_COMMIT] = [${BITBUCKET_COMMIT}]"
            - echo "[BITBUCKET_REPO_OWNER] = [${BITBUCKET_REPO_OWNER}]"
            - echo "[BITBUCKET_REPO_SLUG] = [${BITBUCKET_REPO_SLUG}]"
            - echo "[BITBUCKET_TAG] = [${BITBUCKET_TAG}]"
            - echo "[BITBUCKET_BUILD_NUMBER] = [${BITBUCKET_BUILD_NUMBER}]"
            - echo "[CI] = [${CI}]"
            - printf "[FINISHED] Everything is awesome!\n";

definitions:
  caches:
    apt: /var/cache/apt/
    bower: ./bower_modules/
    node: ./node_modules/
