image: tbaltrushaitis/ubuntu-nodejs:v8.0.0

pipelines:
  default:
    - step:
        script:
          - echo "[Step_00] This script runs on all branches that don't have any specific pipeline assigned in 'branches'.\n"
  branches:
    master:
      - step:
          script:
            - printf "[Step_00] This script runs only on commit to the MASTER branch.\n"
            - uname -a
            - free -m
            - df -H
            - netstat -apn
            - npm -v
            - ls -als
            - pwd
            - printf "Everything is awesome!\n";
    dev-1.0.3:
      - step:
          name: Step_01 - Intro
          script:
            - printf "[Step_01] This script runs only on commit to the [${BITBUCKET_BRANCH}] branch.\n"
            - uname -a
            - pwd
            - printf "[Step_01] ==================================================================== [FINISHED]\n"
      - step:
          name: Step_02 - Update system
          caches:
            - apt
            - bower
            - node
          script:
            - printf "Update system \n"
            - source ./bin/.bash_colors
            - apt-get -y update
      - step:
          name: Step_03 - Install system packages
          caches:
            - apt
          script:
            - apt -y install make
      - step:
          name: Step_04 - PHP setup
          caches:
            - apt
          script:
            - printf "PHP setup \n"
            # PHP setup
            - apt -y install php5 php5-cli php5-common php-db
            - php -v
      - step:
          name: Step_05 - NPM install
          caches:
            - apt
          script:
            - printf "NPM install \n"
            # NPM install
            - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            - export NVM_DIR="$HOME/.nvm"
            # This loads nvm
            - . "$NVM_DIR/nvm.sh"
            - echo -e "\t${BCyan}ENV:\t exported [$NVM_DIR/nvm.sh]"
            # This loads nvm bash_completion
            - . "$NVM_DIR/bash_completion"
      - step:
          name: Step_06 - NODE.JS install
          script:
            - nvm install v8.0.0
            - node -v
      - step:
          name: Step_07 - BUILD project
          caches:
            - bower
            - node
          script:
            - echo "BUILD project"
            - pwd
            # BUILD project
            - make setup
            - make dev
            - sleep 1
            - pwd && ls -als
            - cat webroot/.env
      - step:
          name: Step_08 - Check webroot
          script:
            - cd webroot
            - cat INSPIRATION
      - step:
          name: Step_Last - Information
          script:
            - echo "[Step_Info] Script runs on the [${BITBUCKET_BRANCH}] branch."
            - pwd
            - echo "[BITBUCKET_CLONE_DIR] = [${BITBUCKET_CLONE_DIR}]"
            - echo "[BITBUCKET_COMMIT] = [${BITBUCKET_COMMIT}]"
            - echo "[BITBUCKET_REPO_OWNER] = [${BITBUCKET_REPO_OWNER}]"
            - echo "[BITBUCKET_REPO_SLUG] = [${BITBUCKET_REPO_SLUG}]"
            - echo "[BITBUCKET_TAG] = [${BITBUCKET_TAG}]"
            - echo "[BITBUCKET_BUILD_NUMBER] = [${BITBUCKET_BUILD_NUMBER}]"
            - echo "[CI] = [${CI}]"
            - printf "Everything is awesome!\n";

definitions:
  caches:
    apt: /var/cache/apt/
    bower: ./bower_modules/
    node: ./node_modules/
