image: tbaltrushaitis/ubuntu-nodejs:v8.0.0

pipelines:
  default:
    - step:
        script:
          - echo "[Step_00] This script runs on all branches that don't have any specific pipeline assigned in 'branches'.\n"
  branches:
    master:
      - step:
          script:
            - printf "[Step_00] This script runs only on commit to the MASTER branch.\n"
            - uname -a
            - free -m
            - df -H
            - netstat -apn
            - npm -v
            - ls -als
            - pwd
            - printf "Everything is awesome!\n";
    dev-1.0.3:
      - step:
          script:
            - printf "[Step_01] This script runs only on commit to the [${BITBUCKET_BRANCH}] branch.\n"
            - uname -a
            - pwd
            - printf "[Step_01] ==================================================================== [FINISHED]\n"
      - step:
          caches:
            - apt
            - bower
            - node
          script:
            - printf "[Step_02] This script run for the [${BITBUCKET_BRANCH}] branch.\n"
            - source ./bin/.bash_colors
            - apt-get update -y
            # PHP setup
            - apt -y install php5 php5-cli php5-common php-db
            - php -v
            # NPM install
            - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            - export NVM_DIR="$HOME/.nvm"
            # This loads nvm
            # - [ -s "$NVM_DIR/nvm.sh" ]
            - . "$NVM_DIR/nvm.sh"
            - echo -e "\t${BCyan}ENV:\t exported [$NVM_DIR/nvm.sh]"
            # This loads nvm bash_completion
            # - [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" && echo -e "\t${BCyan}ENV:\t exported [$NVM_DIR/bash_completion]"
            - . "$NVM_DIR/bash_completion"
            - nvm install v8.0.0
            - sleep 1
            # BUILD project
            - make all
            - sleep 1
            - pwd && ls -als
            # - ./setup.sh test --env=production
            # - ./setup.sh prepare --env=production
            # - ./setup.sh build --env=production
            # - ./setup.sh deploy --env=production
      - step:
          script:
            - echo "[Step_03] Script runs on the [${BITBUCKET_BRANCH}] branch."
            - pwd
            - echo "[BITBUCKET_CLONE_DIR] = [${BITBUCKET_CLONE_DIR}]"
            - echo "[BITBUCKET_COMMIT] = [${BITBUCKET_COMMIT}]"
            - echo "[BITBUCKET_REPO_OWNER] = [${BITBUCKET_REPO_OWNER}]"
            - echo "[BITBUCKET_REPO_SLUG] = [${BITBUCKET_REPO_SLUG}]"
            - echo "[BITBUCKET_TAG] = [${BITBUCKET_TAG}]"
            - echo "[BITBUCKET_BUILD_NUMBER] = [${BITBUCKET_BUILD_NUMBER}]"
            - echo "[CI] = [${CI}]"
            # - apt-get update -y
            # - apt -y install php5 php5-cli php5-common
            # - php -v
            # - make all
            # - pwd && ls -als
            # - cat webroot/.env
            - printf "Everything is awesome!\n";

definitions:
  caches:
    bower: ./bower_modules/
    apt: /var/cache/apt/
